class Product {
  final int id;
  final String name;
  final String description;
  final int quantity;
  final String barcode;
  final DateTime createdAt;
  final DateTime updatedAt;
  final String createdBy;
  final String lastModifiedBy;
  final int locationId;
  final String locationName;
  final int categoryId;
  final String categoryName;
  final int? imageId;

  Product({
    required this.id,
    required this.name,
    required this.description,
    required this.quantity,
    required this.barcode,
    required this.createdAt,
    required this.updatedAt,
    required this.createdBy,
    required this.lastModifiedBy,
    required this.locationId,
    required this.locationName,
    required this.categoryId,
    required this.categoryName,
    this.imageId,
  });

  // Factory constructor to create a Product from JSON
  factory Product.fromJson(Map<String, dynamic> json) {
    return Product(
      id: json['id'] is String ? int.parse(json['id']) : json['id'],
      name: json['name'],
      description: json['description'],
      quantity: json['quantity'] is String ? int.parse(json['quantity']) : json['quantity'],
      barcode: json['barcode'],
      createdAt: DateTime.parse(json['createdAt']),
      updatedAt: DateTime.parse(json['updatedAt']),
      createdBy: json['createdBy'],
      lastModifiedBy: json['lastModifiedBy'],
      locationId: json['locationId'] is String ? int.parse(json['locationId']) : json['locationId'],
      locationName: json['locationName'],
      categoryId: json['categoryId'] is String ? int.parse(json['categoryId']) : json['categoryId'],
      categoryName: json['categoryName'],
      imageId: json['imageId'] != null 
          ? (json['imageId'] is String ? int.parse(json['imageId']) : json['imageId']) 
          : null,
    );
  }

  // Convert Product to JSON
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'description': description,
      'quantity': quantity,
      'barcode': barcode,
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
      'createdBy': createdBy,
      'lastModifiedBy': lastModifiedBy,
      'locationId': locationId,
      'locationName': locationName,
      'categoryId': categoryId,
      'categoryName': categoryName,
      'imageId': imageId,
    };
  }
  
  // Create a new product request (without the fields that are generated by the server)
  Map<String, dynamic> toCreateRequest() {
    return {
      'name': name,
      'description': description,
      'quantity': quantity,
      'barcode': barcode,
      'locationId': locationId,
      'categoryId': categoryId,
    };
  }
  
  // Create a copy of this product with updated fields
  Product copyWith({
    int? id,
    String? name,
    String? description,
    int? quantity,
    String? barcode,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? createdBy,
    String? lastModifiedBy,
    int? locationId,
    String? locationName,
    int? categoryId,
    String? categoryName,
    int? imageId,
  }) {
    return Product(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      quantity: quantity ?? this.quantity,
      barcode: barcode ?? this.barcode,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      createdBy: createdBy ?? this.createdBy,
      lastModifiedBy: lastModifiedBy ?? this.lastModifiedBy,
      locationId: locationId ?? this.locationId,
      locationName: locationName ?? this.locationName,
      categoryId: categoryId ?? this.categoryId,
      categoryName: categoryName ?? this.categoryName,
      imageId: imageId ?? this.imageId,
    );
  }
}